
export const reportCategories = [
  'Dywidenda',
  'Działalność finansowa',
  'Emisja akcji',
  'Emisja lub wykup obligacji',
  'Grupa kapitałowa',
  'Klasyfikacje giełdowe',
  'Koncesje, kontrole, regulacje',
  'Pozostałe',
  'Rozwój firmy',
  'Skup lub zbycie akcji własnych',
  'Split',
  'Spory, procesy, windykacja',
  'Sprawy kadrowe',
  'Terminy raportów okresowych',
  'Transakcje animatora',
  'Transakcje insidera',
  'Transakcje insidera lub znaczącego inwestora',
  'Transakcje pakietowe',
  'Walne Zgromadzenie',
  'Wejście znaczącego inwestora lub insidera',
  'Wyjście znaczącego inwestora lub insidera',
  'Wyniki',
  'Zdarzenia losowe',
  'Zmiana strategii',
  'Zmiany w kadrze zarządzającej',
  'Znacząca umowa'
];
